name = "CIMOptimizer"
uuid = "f763a312-2f8b-4ea4-ad8b-371148ce3a7b"
authors = ["pedromxavier <pedrox@cos.ufrj.br>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"

[compat]
PythonCall = "0.9"
QUBODrivers = "0.2"
julia = "1.6"
